const LABEL_BABYSITTER = 'BABYSITTER';

const LABEL_DELETE = 'DELETE';

const LABEL_EDIT = 'EDIT';

const LABEL_EMAIL = 'EMAIL';

const LABEL_EMPTY_PROFILES = 'NO PROFILES';

const LABEL_FIRST_NAME = 'FIRST NAME';

const LABEL_LAST_NAME = 'LAST NAME';

const LABEL_LOG_IN = 'LOG IN';

const LABEL_NAME = 'NAME';

const LABEL_NUMBER = 'NUMBER';

const LABEL_PARENT = 'PARENT';

const LABEL_PASSWORD = 'PASSWORD';

const LABEL_REGISTER = 'REGISTER';

const LABEL_RELOAD = 'RELOAD';

const LABEL_TYPE = 'TYPE';

const LABEL_USERNAME = 'USERNAME';

const MESSAGE_PROFILES_LOAD_FAIL = 'FAILED TO LOAD PROFILES!';

const MESSAGE_LOG_IN_FAIL = 'FAILED TO LOG IN!';

const MESSAGE_LOG_IN_SUCCESS = 'LOG-IN SUCCESSFUL!';

const MESSAGE_LOG_IN_TRY = 'TRYING TO LOG IN...';

const MESSAGE_REGISTRATION_FAIL = 'FAILED TO REGISTER NEW USER!';

const MESSAGE_REGISTRATION_SUCCESS = 'SUCCESSFULLY REGISTERED USER!';

const MESSAGE_REGISTRATION_TRY = 'TRYING TO REGISTER NEW USER...';

const TITLE_APP = 'iCare';

const TITLE_LOG_IN = 'Log In';

const TITLE_REGISTER = 'Register';

const WARNING_NOT_LOGGED = 'YOU ARE NOT LOGGED IN!';

const StringsEnglish = Object.freeze({
    LABEL_BABYSITTER,
    LABEL_DELETE,
    LABEL_EDIT,
    LABEL_EMAIL,
    LABEL_EMPTY_PROFILES,
    LABEL_FIRST_NAME,
    LABEL_LAST_NAME,
    LABEL_LOG_IN,
    LABEL_NAME,
    LABEL_NUMBER,
    LABEL_PARENT,
    LABEL_PASSWORD,
    LABEL_REGISTER,
    LABEL_RELOAD,
    LABEL_TYPE,
    LABEL_USERNAME,
    MESSAGE_LOG_IN_FAIL,
    MESSAGE_LOG_IN_SUCCESS,
    MESSAGE_LOG_IN_TRY,
    MESSAGE_PROFILES_LOAD_FAIL,
    MESSAGE_REGISTRATION_FAIL,
    MESSAGE_REGISTRATION_SUCCESS,
    MESSAGE_REGISTRATION_TRY,
    TITLE_APP,
    TITLE_LOG_IN,
    TITLE_REGISTER,
    WARNING_NOT_LOGGED,
});

export default StringsEnglish;