# Generated by Django 3.2.5 on 2022-05-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0004_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('babysitter_id', models.IntegerField()),
                ('job_id', models.IntegerField()),
                ('cover_letter', models.TextField()),
            ],
        ),
    ]
