# Generated by Django 4.0.6 on 2022-07-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0010_rename_full_name_registration_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='child_care',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='school_help',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
