# Generated by Django 4.0.4 on 2022-07-27 07:32

import datastore.models.registrations
import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('datastore', '0020_rename_babysitter_id_application_from_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('user_number', models.IntegerField(primary_key=True, serialize=False)),
                ('sun_mor', models.BooleanField(default=False)),
                ('sun_aft', models.BooleanField(default=False)),
                ('sun_eve', models.BooleanField(default=False)),
                ('sun_nig', models.BooleanField(default=False)),
                ('mon_mor', models.BooleanField(default=False)),
                ('mon_aft', models.BooleanField(default=False)),
                ('mon_eve', models.BooleanField(default=False)),
                ('mon_nig', models.BooleanField(default=False)),
                ('tue_mor', models.BooleanField(default=False)),
                ('tue_aft', models.BooleanField(default=False)),
                ('tue_eve', models.BooleanField(default=False)),
                ('tue_nig', models.BooleanField(default=False)),
                ('wed_mor', models.BooleanField(default=False)),
                ('wed_aft', models.BooleanField(default=False)),
                ('wed_eve', models.BooleanField(default=False)),
                ('wed_nig', models.BooleanField(default=False)),
                ('thu_mor', models.BooleanField(default=False)),
                ('thu_aft', models.BooleanField(default=False)),
                ('thu_eve', models.BooleanField(default=False)),
                ('thu_nig', models.BooleanField(default=False)),
                ('fri_mor', models.BooleanField(default=False)),
                ('fri_aft', models.BooleanField(default=False)),
                ('fri_eve', models.BooleanField(default=False)),
                ('fri_nig', models.BooleanField(default=False)),
                ('sat_mor', models.BooleanField(default=False)),
                ('sat_aft', models.BooleanField(default=False)),
                ('sat_eve', models.BooleanField(default=False)),
                ('sat_nig', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=datastore.models.registrations.content_file_user),
        ),
        migrations.AddField(
            model_name='registration',
            name='child_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='have_children',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='have_drive_license',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='have_experience_special',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='help_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='house_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='remotely',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='smoking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='street_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='post_time',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='time_a',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='time_b',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='child_care',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='exp_years',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='num_of_children',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='school_help',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registration',
            name='short_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='username',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
