USERNAME = 'username'
EMAIL = 'email'
PASSWORD = 'password'
FIRST_NAME = 'first_name'
LAST_NAME = 'last_name'
ERROR_CODE = 'error_code'
SESSION = 'session_key'
REGISTRATION_TYPE = 'registration_type'
TITLE = 'title'
DESCRIPTION = 'description'
TIME_A = 'time_a'
TIME_B = 'time_b'
NUMBER_JOB = 'number_job'
NUMBER_PARENT = 'number_parent'
NUMBER_USER = 'number_user'

